# Generated by Django 5.2 on 2025-09-05 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio_por_noche', models.CharField(max_length=255)),
                ('capacidad', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='habitaciones/')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=255)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entrada', models.DateTimeField()),
                ('salida', models.DateTimeField()),
                ('monto_total', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(max_length=255)),
                ('codigo_qr', models.TextField()),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.PositiveIntegerField(default=0)),
                ('metodo_de_pago', models.CharField(max_length=255)),
                ('id_transaccion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.rol')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.usuario'),
        ),
    ]
